"""Print the DDL and registry seed a results database needs — for a DBA to run.

Nothing in this system creates these tables: the runtime principal that publishes results is not
one that can define them.

    python -m chemclaw.cli.sink_schema             # the DDL
    python -m chemclaw.cli.sink_schema --seed      # the registry rows the DDL needs to be usable
    python -m chemclaw.cli.sink_schema --all       # both, in the order they must be applied

The seed is generated from `chemclaw.publish.properties` and `chemclaw.publish.solvents`, the
modules the writer canonicalizes against, so its foreign keys cannot drift from them.
"""

import argparse
import sys
from pathlib import Path

from chemclaw.publish.properties import REGISTRY
from chemclaw.publish.record import Conditions
from chemclaw.publish.solvents import display_name, known_solvents

_SCHEMA_DIR = Path(__file__).resolve().parents[3] / "schema" / "result-store"


def _quote(value: str) -> str:
    """A SQL string literal with single quotes doubled.

    The values come from modules in this repository, never from a caller, so doubling apostrophes is
    the only escaping needed.
    """
    return "'" + value.replace("'", "''") + "'"


def ddl() -> str:
    """Every shipped migration, concatenated in order."""
    files = sorted(_SCHEMA_DIR.glob("*.sql"))
    if not files:
        raise SystemExit(f"no schema files found in {_SCHEMA_DIR}")
    return "\n\n".join(path.read_text(encoding="utf-8") for path in files)


def seed() -> str:
    """The registry rows, as idempotent INSERTs.

    `ON CONFLICT DO NOTHING` throughout, so re-applying after an upgrade adds new properties and
    leaves existing ones alone.
    """
    lines = [
        "-- Generated by `python -m chemclaw.cli.sink_schema --seed`. Do not hand-edit: the source",
        "-- is `chemclaw.publish.properties` and `chemclaw.publish.solvents`, which is also what",
        "-- the writer canonicalizes against. A seed that drifted from them would build a database",
        "-- whose foreign keys reject rows this system considers valid.",
        "",
        "-- Every quantity that may be published, with the unit it is kept in.",
    ]
    for definition in sorted(REGISTRY.values(), key=lambda d: d.property):
        lines.append(
            "INSERT INTO property_definition "
            "(property, dimension, canonical_unit, value_kind, scope_kind, definition) VALUES ("
            f"{_quote(definition.property)}, {_quote(definition.dimension)}, "
            f"{_quote(definition.canonical_unit)}, {_quote(definition.value_kind)}, "
            f"{_quote(definition.scope_kind)}, {_quote(definition.definition)}"
            ") ON CONFLICT DO NOTHING;"
        )
    lines += [
        "",
        "-- Canonical solvents and every accepted spelling. Without the alias rows, a query for",
        "-- one solvent silently misses every run submitted under another of its names.",
    ]
    for canonical, aliases in sorted(known_solvents().items()):
        lines.append(
            "INSERT INTO solvent (solvent_id, display_name) VALUES ("
            f"{_quote(canonical)}, {_quote(display_name(canonical))}"
            ") ON CONFLICT DO NOTHING;"
        )
        for alias in sorted(aliases):
            lines.append(
                "INSERT INTO solvent_alias (alias, solvent_id) VALUES ("
                f"{_quote(alias)}, {_quote(canonical)}"
                ") ON CONFLICT DO NOTHING;"
            )
    lines += [
        "",
        "-- The condition set every calculator with no conditions of its own points at. A real row",
        "-- rather than a null, so 'ran in the gas phase' and 'this calculator has no conditions'",
        "-- are one queryable value instead of a LEFT JOIN in every consumer.",
        "--",
        "-- **The id is derived, not chosen.** This row is the writer's own empty `Conditions`,",
        "-- whose `condition_id` is a content hash like every other key in this schema. It was",
        "-- seeded as the literal 'cond_unspecified' and the writer has always upserted the hash,",
        "-- so a consumer following the advice above and joining on that name got zero rows,",
        "-- forever, while the row it wanted sat beside it under another id. Generated from the",
        "-- model rather than written out, so the two cannot part company if the hash basis moves.",
        "INSERT INTO condition_set (condition_id, solvent_model) VALUES "
        f"({_quote(Conditions().condition_id)}, '') ON CONFLICT DO NOTHING;",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Print the DDL, the seed, or both."""
    parser = argparse.ArgumentParser(
        prog="python -m chemclaw.cli.sink_schema",
        description=(
            "Print the SQL a results database needs. Apply it with your own tooling: this system "
            "never holds DDL privileges on the store it publishes to."
        ),
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--seed", action="store_true", help="only the registry rows")
    group.add_argument("--all", action="store_true", help="the DDL then the registry rows")
    args = parser.parse_args(argv)

    if args.seed:
        sys.stdout.write(seed())
    elif args.all:
        sys.stdout.write(ddl())
        sys.stdout.write("\n\n")
        sys.stdout.write(seed())
    else:
        sys.stdout.write(ddl())
    return 0


if __name__ == "__main__":  # pragma: no cover - entry point
    raise SystemExit(main())
