"""Print the DDL and registry seed a results database needs — for a DBA to run.

**Nothing in this system ever creates these tables.** The runtime principal that publishes results
every day is not the principal that can define them, which is the same split this repository
already makes for its own database (`postgres_migration_dsn` against `postgres_dsn`). So the shape
of the store ships as SQL and a person applies it.

    python -m chemclaw.cli.sink_schema             # the DDL
    python -m chemclaw.cli.sink_schema --seed      # the registry rows the DDL needs to be usable
    python -m chemclaw.cli.sink_schema --all       # both, in the order they must be applied

The seed is generated from `chemclaw.publish.properties` and `chemclaw.publish.solvents` rather
than kept as a second copy in SQL: those modules are what the writer canonicalizes against, and a
seed file that drifted from them would produce a database whose foreign keys reject rows this
system considers valid.
"""

import argparse
import sys
from pathlib import Path

from chemclaw.publish.properties import REGISTRY
from chemclaw.publish.solvents import display_name, known_solvents

_SCHEMA_DIR = Path(__file__).resolve().parents[3] / "schema" / "result-store"


def _quote(value: str) -> str:
    """A SQL string literal. Single quotes doubled — the only escaping this generator needs.

    The values are property names, units and prose definitions from a module in this repository,
    not anything a caller supplied, so there is no injection surface here; the doubling is for
    apostrophes in the English.
    """
    return "'" + value.replace("'", "''") + "'"


def ddl() -> str:
    """Every shipped migration, concatenated in order."""
    files = sorted(_SCHEMA_DIR.glob("*.sql"))
    if not files:
        raise SystemExit(f"no schema files found in {_SCHEMA_DIR}")
    return "\n\n".join(path.read_text(encoding="utf-8") for path in files)


def seed() -> str:
    """The registry rows, as idempotent INSERTs.

    Re-runnable: `ON CONFLICT DO NOTHING` throughout, so applying this after an upgrade adds the
    new properties and leaves the existing ones alone. That is the whole extension story — a new
    calculator ships new rows here and the DDL does not move.
    """
    lines = [
        "-- Generated by `python -m chemclaw.cli.sink_schema --seed`. Do not hand-edit: the source",
        "-- is `chemclaw.publish.properties` and `chemclaw.publish.solvents`, which is also what",
        "-- the writer canonicalizes against. A seed that drifted from them would build a database",
        "-- whose foreign keys reject rows this system considers valid.",
        "",
        "-- Every quantity that may be published, with the unit it is kept in.",
    ]
    for definition in sorted(REGISTRY.values(), key=lambda d: d.property):
        lines.append(
            "INSERT INTO property_definition "
            "(property, dimension, canonical_unit, value_kind, scope_kind, definition) VALUES ("
            f"{_quote(definition.property)}, {_quote(definition.dimension)}, "
            f"{_quote(definition.canonical_unit)}, {_quote(definition.value_kind)}, "
            f"{_quote(definition.scope_kind)}, {_quote(definition.definition)}"
            ") ON CONFLICT DO NOTHING;"
        )
    lines += [
        "",
        "-- Canonical solvents and every accepted spelling. Without the alias rows, a query for",
        "-- one solvent silently misses every run submitted under another of its names.",
    ]
    for canonical, aliases in sorted(known_solvents().items()):
        lines.append(
            "INSERT INTO solvent (solvent_id, display_name) VALUES ("
            f"{_quote(canonical)}, {_quote(display_name(canonical))}"
            ") ON CONFLICT DO NOTHING;"
        )
        for alias in sorted(aliases):
            lines.append(
                "INSERT INTO solvent_alias (alias, solvent_id) VALUES ("
                f"{_quote(alias)}, {_quote(canonical)}"
                ") ON CONFLICT DO NOTHING;"
            )
    lines += [
        "",
        "-- The condition set every calculator with no conditions of its own points at. A real row",
        "-- rather than a null, so 'ran in the gas phase' and 'this calculator has no conditions'",
        "-- are one queryable value instead of a LEFT JOIN in every consumer.",
        "INSERT INTO condition_set (condition_id, solvent_model) VALUES "
        "('cond_unspecified', '') ON CONFLICT DO NOTHING;",
    ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Print the DDL, the seed, or both."""
    parser = argparse.ArgumentParser(
        prog="python -m chemclaw.cli.sink_schema",
        description=(
            "Print the SQL a results database needs. Apply it with your own tooling: this system "
            "never holds DDL privileges on the store it publishes to."
        ),
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--seed", action="store_true", help="only the registry rows")
    group.add_argument("--all", action="store_true", help="the DDL then the registry rows")
    args = parser.parse_args(argv)

    if args.seed:
        sys.stdout.write(seed())
    elif args.all:
        sys.stdout.write(ddl())
        sys.stdout.write("\n\n")
        sys.stdout.write(seed())
    else:
        sys.stdout.write(ddl())
    return 0


if __name__ == "__main__":  # pragma: no cover - entry point
    raise SystemExit(main())
